import Header from "@/components/Header";
import "./globals.css";
import Rodape from "@/components/Rodape";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
